### ISSUE TITLE
Another installation Error:

### ISSUE THREAD

**Issue by AlexCppns** [odakahirokazu/RubyROOT#2]
$ make
[ 50%] Swig source
Scanning dependencies of target root
[100%] Building CXX object ruby/CMakeFiles/root.dir/rootRUBY_wrap.cxx.o
/home/zelrik/RubyROOT/ruby/rootRUBY_wrap.cxx:2130:35: fatal error: Math/MinimizerOptions.h: No such file or directory
compilation terminated.
make[2]: **\* [ruby/CMakeFiles/root.dir/rootRUBY_wrap.cxx.o] Error 1
make[1]: **\* [ruby/CMakeFiles/root.dir/all] Error 2
make: **\* [all] Error 2

**Comment by odakahirokazu** [comment]
If minuit2 is not enabled in ROOT, cmake option ENABLE_MINUIT2=OFF would help.
