### ISSUE TITLE
Binning for log-acaled axis with TH1

### ISSUE THREAD

**Issue by YuukiWada** [odakahirokazu/RubyROOT#9]
Hi @yuasatakayuki and @odakahirokazu 

In the case of TH1, we can assign variable bins with an array "xbins" like
`TH1D.create(name, title, nbinsx, xbins)`.

I wrote a sample code below.
```
energyMin=0.1
energyMax=15.0
logEnergyMin=log(energyMin, 10)
logEnergyMax=log(energyMax, 10)
binNum=40
binWidth=(logEnergyMax-logEnergyMin)/binNum
xbins=Array.new

(binNum+1).times do |nbin|
  xbins[nbin]=10**(logEnergyMin+nbin*binWidth)
end

spectrum=Root::TH1D.create("spectrum", "spectrum", binNum, xbins)
```
Then an error generated.
> `create': Wrong arguments for overloaded method 'create'. (ArgumentError)
> Possible C/C++ prototypes are:
>     TH1D * create(char const *name, char const *title, Int_t nbinsx, Double_t xlow, Double_t xup)
>     TH1D * create(char const *name, char const *title, Int_t nbinsx, Double_t const *xbins)

Could you tell me how to resolve this problem?

**Comment by yuasatakayuki** [comment]
Hi @YuukiWada 

Use `Root::DoubleArray` class to construct a double array passed to C++ methods/constructors that accept `double*`-type array. 

The `DoubleArray` class is automatically generated by using SWIG's `carray.i` library. You may want to take a look at `carray.i` documentation at http://www.swig.org/Doc3.0/SWIGDocumentation.html#Library_carrays . `root.i` is the place where `DoubleArray` is declared in RubyROOT.

Here's an example:

```
require "RubyROOT"

nBins = 10

xBins = Root::DoubleArray.new(nBins+1)

for i in 0..nBins do
    xBins[i] = i**2
end

spectrum = Root::TH1D.create("spectrum", "spectrum", nBins, xBins)

for i in 0...nBins do
    puts "Bin #{i} Bin Center #{spectrum.GetXaxis().GetBinCenter(i)}"
end
```

When executed, you'll get something like the following:

```
$ ruby a
Bin 0 Bin Center -5.0
Bin 1 Bin Center 0.5
Bin 2 Bin Center 2.5
Bin 3 Bin Center 6.5
Bin 4 Bin Center 12.5
Bin 5 Bin Center 20.5
Bin 6 Bin Center 30.5
Bin 7 Bin Center 42.5
Bin 8 Bin Center 56.5
Bin 9 Bin Center 72.5
```

**Comment by YuukiWada** [comment]
Hi @yuasatakayuki 
Thank you for your comment.
The problem has been resolved with the `DoubleArray` class.
The analysis is ongoing...
